import 'dart:convert';

import 'package:ostadclassagain2/module_16/utils/urils.dart';

import 'model/product_model.dart';
import 'package:http/http.dart' as http;
class Productcontroller{
  List<Data>products=[];
  Future fetchusers()async{
    final response =await http.get(Uri.parse(Urls.readproduct));
    if(response.statusCode==200)
      {
        final data=jsonDecode(response.body);
        Autogenerated model=Autogenerated.fromJson(data);
        products=model.data??[];
      }
  }
}